import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from '../components/Header';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';

interface Props {
  blogs: {
    id: number,
    title: string,
    description: string
  }[]
}
const Home: NextPage = (props: Props) => {
  const { blogs } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
      </main >
      <ul>
        {
          blogs.map((item) => {
            return (
              <li key={item.title}>{item.title}</li>
            );
          })

        }
      </ul>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div >
  );
};

export default Home;

export const getServerSideProps = async () => {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_DELIVERY_TOKEN}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: `
        query {
            blogCollection{
              items{
                title
                description
              }
            }
        }`
    })
  });
  const { data } = await result.json();
  const blogs = data.blogCollection.items;
  return { props: { blogs } };
};